=== filipmares/vscode-specialsboard-theme/schemas/vscode-theme.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://specialsboard.local/schemas/vscode-theme",
  "type": "object",
  "required": ["$schema", "name", "author", "type", "colors", "tokenColors"],
  "additionalProperties": false,
  "properties": {
    "$schema": { "const": "vscode://schemas/color-theme" },
    "name": { "type": "string", "minLength": 1 },
    "author": { "const": "Filip Mares" },
    "type": { "const": "dark" },
    "colors": {
      "type": "object",
      "minProperties": 1,
      "additionalProperties": { "$ref": "#/definitions/color" }
    },
    "tokenColors": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "required": ["scope", "settings"],
        "additionalProperties": false,
        "properties": {
          "name": { "type": "string" },
          "scope": { "$ref": "vscode-mapping#/properties/textMate/items/properties/scope" },
          "settings": {
            "type": "object",
            "minProperties": 1,
            "additionalProperties": false,
            "properties": {
              "foreground": { "$ref": "#/definitions/color" },
              "background": { "$ref": "#/definitions/color" },
              "fontStyle": { "$ref": "vscode-mapping#/properties/textMate/items/properties/settings/properties/fontStyle" }
            }
          }
        }
      }
    },
    "semanticHighlighting": { "const": true },
    "semanticTokenColors": {
      "type": "object",
      "minProperties": 1,
      "additionalProperties": {
        "oneOf": [
          { "$ref": "#/definitions/color" },
          {
            "type": "object",
            "minProperties": 1,
            "additionalProperties": false,
            "properties": {
              "foreground": { "$ref": "#/definitions/color" },
              "bold": { "type": "boolean" },
              "italic": { "type": "boolean" },
              "underline": { "type": "boolean" },
              "strikethrough": { "type": "boolean" }
            }
          }
        ]
      }
    }
  },
  "dependencies": {
    "semanticHighlighting": ["semanticTokenColors"],
    "semanticTokenColors": ["semanticHighlighting"]
  },
  "definitions": {
    "color": { "type": "string", "pattern": "^#[0-9a-f]{6}([0-9a-f]{2})?$" }
  }
}

=== filipmares/vscode-specialsboard-theme/tests/fixtures/phase0-theme.json
{
  "$schema": "vscode://schemas/color-theme",
  "name": "Specials Board",
  "author": "Filip Mares",
  "type": "dark",
  "colors": {
    "editor.background": "#383939",
    "editorCursor.foreground": "#e6e1dc",
    "editor.foreground": "#FFFFFF",
    "editorWhitespace.foreground": "#434343",
    "editor.lineHighlightBackground": "#2e2d2d",
    "editor.selectionBackground": "#6c99bb33",
    "badge.background": "#d0663a",
    "activityBar.background": "#2e2d2d",
    "activityBarBadge.background": "#d0663a",
    "tab.activeBackground": "#383939",
    "tab.activeForeground": "#FFFFFF",
    "tab.border": "#2e2d2d",
    "tab.hoverBackground": "#676869",
    "tab.inactiveBackground": "#2e2d2d",
    "tab.unfocusedHoverBackground": "#676869",
    "sideBar.background": "#2e2d2d",
    "sideBarSectionHeader.background": "#2e2d2d",
    "list.activeSelectionBackground": "#383939",
    "list.activeSelectionForeground": "#ffffff",
    "list.hoverBackground": "#676869",
    "list.inactiveSelectionBackground": "#676869",
    "terminal.ansiBlack": "#2d3139",
    "terminal.ansiBlue": "#5286b7",
    "terminal.ansiBrightBlack": "#7f848e",
    "terminal.ansiBrightBlue": "#86a9c4",
    "terminal.ansiBrightCyan": "#86a9c4",
    "terminal.ansiBrightGreen": "#b9c87f",
    "terminal.ansiBrightMagenta": "#a97a8c",
    "terminal.ansiBrightRed": "#ac4639",
    "terminal.ansiBrightWhite": "#d9dbfc",
    "terminal.ansiBrightYellow": "#c4bc3c",
    "terminal.ansiCyan": "#86a9c4",
    "terminal.ansiGreen": "#b9c87f",
    "terminal.ansiMagenta": "#a97a8c",
    "terminal.ansiRed": "#ac4639",
    "terminal.ansiWhite": "#d9dbfc",
    "terminal.ansiYellow": "#c4bc3c",
    "terminal.foreground": "#d9dbfc",
    "statusBar.background": "#383939",
    "statusBar.debuggingBackground": "#383939",
    "statusBar.debuggingBorder": "#383939",
    "statusBar.debuggingForeground": "#ffffff",
    "statusBar.foreground": "#e6e1dc",
    "statusBar.noFolderBackground": "#383939",
    "statusBarItem.hoverBackground": "#676869",
    "statusBarItem.remoteBackground": "#5286b7",
    "statusBarItem.remoteForeground": "#e6e1dc"
  },
  "tokenColors": [
    {
      "name": "[VSCODE-CUSTOM] Markdown Quote",
      "scope": "markup.quote.markdown",
      "settings": {
        "foreground": "#b9c87f"
      }
    },
    {
      "name": "Comments",
      "scope": "comment, punctuation.definition.comment",
      "settings": {
        "fontStyle": "italic",
        "foreground": "#b9a370"
      }
    },
    {
      "name": "meta.brace.square",
      "scope": [
        " meta.brace.square"
      ],
      "settings": {
        "foreground": "#abb2bf"
      }
    },
    {
      "name": "Markdown underscore-style headers",
      "scope": [
        "entity.name.label.cs",
        "markup.heading.setext.1.markdown",
        "markup.heading.setext.2.markdown"
      ],
      "settings": {
        "foreground": "#d19a66"
      }
    },
    {
      "name": "styling css pseudo-elements/classes to be able to differentiate from classes which are the same colour",
      "scope": [
        "entity.other.attribute-name.pseudo-element",
        "entity.other.attribute-name.pseudo-class"
      ],
      "settings": {
        "foreground": "#d19a66"
      }
    },
    {
      "name": "html/pug (jade) escaped characters and entities",
      "scope": [
        "constant.character.entity"
      ],
      "settings": {
        "foreground": "#e06c75"
      }
    },
    {
      "name": "template literal",
      "scope": [
        "punctuation.quasi.element"
      ],
      "settings": {
        "foreground": "#c678dd"
      }
    },
    {
      "name": "js operator.assignment",
      "scope": [
        "keyword.operator.assignment"
      ],
      "settings": {
        "foreground": "#c4bc3c"
      }
    },
    {
      "name": "js template literals variable braces end",
      "scope": [
        "keyword.other.substitution.end"
      ],
      "settings": {
        "foreground": "#98c379"
      }
    },
    {
      "name": "js template literals variable braces begin",
      "scope": [
        "keyword.other.substitution.begin"
      ],
      "settings": {
        "foreground": "#98c379"
      }
    },
    {
      "name": "js template literals end",
      "scope": [
        "keyword.other.template.end"
      ],
      "settings": {
        "foreground": "#98c379"
      }
    },
    {
      "name": "js template literals begin",
      "scope": [
        "keyword.other.template.begin"
      ],
      "settings": {
        "foreground": "#98c379"
      }
    },
    {
      "name": "js func parameter",
      "scope": [
        "variable.parameter.function.js"
      ],
      "settings": {
        "foreground": "#e06c75"
      }
    },
    {
      "name": "js class prop",
      "scope": [
        "meta.property.object"
      ],
      "settings": {
        "foreground": "#e06c75"
      }
    },
    {
      "name": "js Flow",
      "scope": [
        "support.type.primitive"
      ],
      "settings": {
        "foreground": "#c4bc3c"
      }
    },
    {
      "name": "js Flowtype",
      "scope": [
        "support.type.type.flowtype"
      ],
      "settings": {
        "foreground": "#61afef"
      }
    },
    {
      "name": "Import module JS",
      "scope": [
        "keyword.operator.module"
      ],
      "settings": {
        "foreground": "#c678dd"
      }
    },
    {
      "name": "Reset JavaScript string interpolation expression",
      "scope": [
        "meta.template.expression"
      ],
      "settings": {
        "foreground": "#abb2bf"
      }
    },
    {
      "name": "String interpolation",
      "scope": [
        "punctuation.definition.template-expression.begin",
        "punctuation.definition.template-expression.end",
        "punctuation.section.embedded"
      ],
      "settings": {
        "foreground": "#c4bc3c"
      }
    },
    {
      "scope": "token.debug-token",
      "settings": {
        "foreground": "#c678dd"
      }
    },
    {
      "scope": "token.error-token",
      "settings": {
        "foreground": "#f44747"
      }
    },
    {
      "scope": "token.warn-token",
      "settings": {
        "foreground": "#d19a66"
      }
    },
    {
      "scope": "token.info-token",
      "settings": {
        "foreground": "#61afef"
      }
    },
    {
      "name": "block scope",
      "scope": "block.scope.end,block.scope.begin",
      "settings": {
        "foreground": "#abb2bf"
      }
    },
    {
      "name": "ts primitive/builtin types",
      "scope": "support.type.primitive.ts,support.type.builtin.ts,support.type.primitive.tsx,support.type.builtin.tsx",
      "settings": {
        "foreground": "#c4bc3c"
      }
    },
    {
      "name": "sass selector",
      "scope": "selector.sass",
      "settings": {
        "foreground": "#e06c75"
      }
    },
    {
      "name": "rgb value less",
      "scope": "less rgb-value",
      "settings": {
        "foreground": "#d19a66"
      }
    },
    {
      "name": "rgb value",
      "scope": "inline-color-decoration rgb-value",
      "settings": {
        "foreground": "#d19a66"
      }
    },
    {
      "name": "rgb-value",
      "scope": "rgb-value",
      "settings": {
        "foreground": "#56b6c2"
      }
    },
    {
      "name": "brace function",
      "scope": "function.brace",
      "settings": {
        "foreground": "#abb2bf"
      }
    },
    {
      "name": "parameter function js/ts",
      "scope": "function.parameter",
      "settings": {
        "foreground": "#abb2bf"
      }
    },
    {
      "name": "python function support",
      "scope": "support.token.decorator.python,meta.function.decorator.identifier.python",
      "settings": {
        "foreground": "#56b6c2"
      }
    },
    {
      "name": "python function decorator @",
      "scope": "meta.function.decorator.python",
      "settings": {
        "foreground": "#61afef"
      }
    },
    {
      "name": "[VSCODE-CUSTOM] JSON Punctuation for Property Name",
      "scope": "support.type.property-name.json punctuation",
      "settings": {
        "foreground": "#d9dbfc"
      }
    },
    {
      "name": "[VSCODE-CUSTOM] JSON Property Name",
      "scope": "support.type.property-name.json",
      "settings": {
        "foreground": "#d9dbfc"
      }
    },
    {
      "name": "Unimplemented",
      "scope": "invalid.unimplemented",
      "settings": {
        "background": "#a71e17",
        "foreground": "#e6e1dc"
      }
    },
    {
      "name": "Deprecated",
      "scope": "invalid.deprecated",
      "settings": {
        "background": "#a71e17",
        "foreground": "#e6e1dc"
      }
    },
    {
      "name": "Broken",
      "scope": "invalid.broken",
      "settings": {
        "background": "#a71e17",
        "foreground": "#e6e1dc"
      }
    },
    {
      "name": "Illegal",
      "scope": "invalid.illegal.bad-ampersand.html",
      "settings": {
        "background": "#a71e17",
        "foreground": "#e6e1dc"
      }
    },
    {
      "name": "Illegal",
      "scope": "invalid.illegal",
      "settings": {
        "background": "#a71e17",
        "foreground": "#e6e1dc"
      }
    },
    {
      "name": "Embedded",
      "scope": "punctuation.section.embedded.begin,punctuation.section.embedded.end",
      "settings": {
        "foreground": "#c4bc3c"
      }
    },
    {
      "name": "Embedded",
      "scope": "punctuation.section.embedded, variable.interpolation",
      "settings": {
        "foreground": "#e06c75"
      }
    },
    {
      "name": "Escape Characters",
      "scope": "constant.character.escape",
      "settings": {
        "foreground": "#b9c87f"
      }
    },
    {
      "name": "Regular Expressions",
      "scope": "string.regexp",
      "settings": {
        "foreground": "#56b6c2"
      }
    },
    {
      "name": "markup.bold.markdown",
      "scope": "markup.bold.markdown",
      "settings": {
        "fontStyle": "bold",
        "foreground": "#e5c07b"
      }
    },
    {
